# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestCarelog():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_login(self):
        # Test name: Login
        # Step # | name | target | value | comment
        # 1 | open | https://www.carefor.co.kr/login.php |  |
        self.driver.get("https://www.carefor.co.kr/login.php")
        # 2 | setWindowSize | 1267x1791 |  |
        self.driver.set_window_size(1610, 1046)
        # 3 | click | name=ctmnumb |  |
        self.driver.find_element(By.NAME, "ctmnumb").click()
        # 4 | type | name=ctmnumb | 14159000559 |
        self.driver.find_element(By.NAME, "ctmnumb").send_keys("14159000559")
        # 5 | click | name=stmiden |  |
        self.driver.find_element(By.NAME, "stmiden").click()
        # 6 | type | name=stmiden | 장석영 |
        self.driver.find_element(By.NAME, "stmiden").send_keys("장석영")
        # 7 | click | name=stmpass |  |
        self.driver.find_element(By.NAME, "stmpass").click()
        # 8 | type | name=stmpass | 0630 |
        self.driver.find_element(By.NAME, "stmpass").send_keys("0630")
        # 9 | click | css=.btn > input |  |
        self.driver.find_element(By.CSS_SELECTOR, ".btn > input").click()
        # 10 | doubleClick | css=.txt_pos |  |
        element = self.driver.find_element(By.CSS_SELECTOR, ".txt_pos")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        # 11 | click | css=.txt_pos | 알림사항 | 알림창 열렸는 지 확인
        self.driver.find_element(By.CSS_SELECTOR, ".txt_pos").click()
        # 12 | click | css=.btn_area > .btn_type3 |  |
        self.driver.find_element(By.CSS_SELECTOR, ".btn_area > .btn_type3").click()

    def test_logout(self):
        # Test name: Logout
        # Step # | name | target | value | comment
        # 1 | open |
        # https://work.carefor.co.kr/#cGFnZXx7J3R5cGUnOidsZWZ0X3N1YjEnLCAndmlldyc6Jy9wYXRpZW50L3ZpZXcucGF0aWVudF9tYW5hZ2UnfSV7InRpdGxlIjoiMS0xLuyImOq4ieyekOygleuztCDqtIDrpqwiLCJldmFsIjoiNDciLCJtb3ZlX3Njcm9sbCI6dHJ1ZX18bGVmdF9zdWIx
        # |  |
        self.driver.get("https://work.carefor.co.kr/#cGFnZXx7J3R5cGUnOidsZWZ0X3N1YjEnLCAndmlldyc6Jy9wYXRpZW50L3ZpZXcucGF0aWVudF9tYW5hZ2UnfSV7InRpdGxlIjoiMS0xLuyImOq4ieyekOygleuztCDqtIDrpqwiLCJldmFsIjoiNDciLCJtb3ZlX3Njcm9sbCI6dHJ1ZX18bGVmdF9zdWIx")
        # 2 | setWindowSize | 1820x1334 |  |
        self.driver.set_window_size(1610, 1046)
        # 3 | click | css=.top_btn_type3 |  |
        self.driver.find_element(By.CSS_SELECTOR, ".top_btn_type3").click()
        # 4 | type | name=stmpass | 0630 |
        self.driver.find_element(By.NAME, "stmpass").send_keys("0630")

    def test_getWardInfo(self):
        # Test name: GetWardInfo
        # Step # | name | target | value | comment
        # 1 | open |
        # https://work.carefor.co.kr/#cGFnZXx7J3R5cGUnOidsZWZ0X3N1YjEnLCAndmlldyc6Jy9wYXRpZW50L3ZpZXcucGF0aWVudF9tYW5hZ2UnfSV7InRpdGxlIjoiMS0xLuyImOq4ieyekOygleuztCDqtIDrpqwiLCJldmFsIjoiNDciLCJtb3ZlX3Njcm9sbCI6dHJ1ZX18bGVmdF9zdWIx
        # |  |
        self.driver.get("https://work.carefor.co.kr/#cGFnZXx7J3R5cGUnOidsZWZ0X3N1YjEnLCAndmlldyc6Jy9wYXRpZW50L3ZpZXcucGF0aWVudF9tYW5hZ2UnfSV7InRpdGxlIjoiMS0xLuyImOq4ieyekOygleuztCDqtIDrpqwiLCJldmFsIjoiNDciLCJtb3ZlX3Njcm9sbCI6dHJ1ZX18bGVmdF9zdWIx")
        # 2 | setWindowSize | 1756x1791 |  |
        self.driver.set_window_size(1610, 1046)
        # 3 | click | css=.tbl_type1 th:nth-child(2) |  |
        self.driver.find_element(By.CSS_SELECTOR, ".tbl_type1 th:nth-child(2)").click()
        # 4 | click | css=.tbl_type1 th:nth-child(2) |  |
        self.driver.find_element(By.CSS_SELECTOR, ".tbl_type1 th:nth-child(2)").click()
        # 5 | doubleClick | css=.tbl_type1 th:nth-child(2) |  |
        element = self.driver.find_element(By.CSS_SELECTOR, ".tbl_type1 th:nth-child(2)")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        # 6 | click | css=.tbl_type1 th:nth-child(2) |  |
        self.driver.find_element(By.CSS_SELECTOR, ".tbl_type1 th:nth-child(2)").click()
        # 7 | click | css=.tbl_type1 th:nth-child(2) |  |
        self.driver.find_element(By.CSS_SELECTOR, ".tbl_type1 th:nth-child(2)").click()
        # 8 | doubleClick | css=.tbl_type1 th:nth-child(2) |  |
        element = self.driver.find_element(By.CSS_SELECTOR, ".tbl_type1 th:nth-child(2)")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        # 9 | click | css=.btpd:nth-child(3) > .bt_txt_align2 |  |
        self.driver.find_element(By.CSS_SELECTOR, ".btpd:nth-child(3) > .bt_txt_align2").click()
        # 10 | click | css=.btpd:nth-child(3) > .bt_txt_align2 |  |
        self.driver.find_element(By.CSS_SELECTOR, ".btpd:nth-child(3) > .bt_txt_align2").click()
        # 11 | doubleClick | css=.btpd:nth-child(3) > .bt_txt_align2 |  |
        element = self.driver.find_element(By.CSS_SELECTOR, ".btpd:nth-child(3) > .bt_txt_align2")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        # 12 | click | css=.tbl_type1 th:nth-child(4) |  |
        self.driver.find_element(By.CSS_SELECTOR, ".tbl_type1 th:nth-child(4)").click()
        # 13 | click | css=.tbl_type1 th:nth-child(4) |  |
        self.driver.find_element(By.CSS_SELECTOR, ".tbl_type1 th:nth-child(4)").click()
        # 14 | doubleClick | css=.tbl_type1 th:nth-child(4) |  |
        element = self.driver.find_element(By.CSS_SELECTOR, ".tbl_type1 th:nth-child(4)")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        # 15 | click | css=.tbl_type1 td:nth-child(5) |  |
        self.driver.find_element(By.CSS_SELECTOR, ".tbl_type1 td:nth-child(5)").click()
        # 16 | click | css=.tbl_type1 td:nth-child(5) |  |
        self.driver.find_element(By.CSS_SELECTOR, ".tbl_type1 td:nth-child(5)").click()
        # 17 | doubleClick | css=.tbl_type1 td:nth-child(5) |  |
        element = self.driver.find_element(By.CSS_SELECTOR, ".tbl_type1 td:nth-child(5)")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        # 18 | click | css=.tbl_type1 th:nth-child(6) |  |
        self.driver.find_element(By.CSS_SELECTOR, ".tbl_type1 th:nth-child(6)").click()
        # 19 | click | css=.tbl_type1 th:nth-child(6) |  |
        self.driver.find_element(By.CSS_SELECTOR, ".tbl_type1 th:nth-child(6)").click()
        # 20 | doubleClick | css=.tbl_type1 th:nth-child(6) |  |
        element = self.driver.find_element(By.CSS_SELECTOR, ".tbl_type1 th:nth-child(6)")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        # 21 | click | css=.tbl_type1 tr:nth-child(1) > td:nth-child(7) |  |
        self.driver.find_element(By.CSS_SELECTOR, ".tbl_type1 tr:nth-child(1) > td:nth-child(7)").click()
        # 22 | click | css=#patient_info_basic tr:nth-child(2) > th:nth-child(1) |  |
        self.driver.find_element(By.CSS_SELECTOR, "#patient_info_basic tr:nth-child(2) > th:nth-child(1)").click()
        # 23 | click | css=#patient_info_basic tr:nth-child(2) > th:nth-child(1) |  |
        self.driver.find_element(By.CSS_SELECTOR, "#patient_info_basic tr:nth-child(2) > th:nth-child(1)").click()
        # 24 | doubleClick | css=#patient_info_basic tr:nth-child(2) > th:nth-child(1) |  |
        element = self.driver.find_element(By.CSS_SELECTOR, "#patient_info_basic tr:nth-child(2) > th:nth-child(1)")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        # 25 | click | css=tr:nth-child(2) > .btpd:nth-child(2) > .bt_txt_align2 |  |
        self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) > .btpd:nth-child(2) > .bt_txt_align2").click()
        # 26 | click | css=#patient_info_basic tr:nth-child(2) > th:nth-child(3) |  |
        self.driver.find_element(By.CSS_SELECTOR, "#patient_info_basic tr:nth-child(2) > th:nth-child(3)").click()
        # 27 | click | css=#patient_info_basic tr:nth-child(2) > th:nth-child(3) |  |
        self.driver.find_element(By.CSS_SELECTOR, "#patient_info_basic tr:nth-child(2) > th:nth-child(3)").click()
        # 28 | doubleClick | css=#patient_info_basic tr:nth-child(2) > th:nth-child(3) |  |
        element = self.driver.find_element(By.CSS_SELECTOR, "#patient_info_basic tr:nth-child(2) > th:nth-child(3)")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        # 29 | click | css=#patient_info_basic tr:nth-child(2) > td:nth-child(4) |  |
        self.driver.find_element(By.CSS_SELECTOR, "#patient_info_basic tr:nth-child(2) > td:nth-child(4)").click()
        # 30 | click | css=#patient_info_basic tr:nth-child(2) > td:nth-child(4) |  |
        self.driver.find_element(By.CSS_SELECTOR, "#patient_info_basic tr:nth-child(2) > td:nth-child(4)").click()
        # 31 | doubleClick | css=#patient_info_basic tr:nth-child(2) > td:nth-child(4) |  |
        element = self.driver.find_element(By.CSS_SELECTOR, "#patient_info_basic tr:nth-child(2) > td:nth-child(4)")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        # 32 | click | css=#patient_info_basic tr:nth-child(2) > th:nth-child(5) |  |
        self.driver.find_element(By.CSS_SELECTOR, "#patient_info_basic tr:nth-child(2) > th:nth-child(5)").click()
        # 33 | click | css=#patient_info_basic tr:nth-child(2) > th:nth-child(5) |  |
        self.driver.find_element(By.CSS_SELECTOR, "#patient_info_basic tr:nth-child(2) > th:nth-child(5)").click()
        # 34 | doubleClick | css=#patient_info_basic tr:nth-child(2) > th:nth-child(5) |  |
        element = self.driver.find_element(By.CSS_SELECTOR, "#patient_info_basic tr:nth-child(2) > th:nth-child(5)")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        # 35 | click | css=.dotdotdot:nth-child(6) |  |
        self.driver.find_element(By.CSS_SELECTOR, ".dotdotdot:nth-child(6)").click()
        # 36 | click | css=#patient_info_basic tr:nth-child(3) > th:nth-child(1) |  |
        self.driver.find_element(By.CSS_SELECTOR, "#patient_info_basic tr:nth-child(3) > th:nth-child(1)").click()
        # 37 | click | css=#patient_info_basic tr:nth-child(3) > th:nth-child(1) |  |
        self.driver.find_element(By.CSS_SELECTOR, "#patient_info_basic tr:nth-child(3) > th:nth-child(1)").click()
        # 38 | doubleClick | css=#patient_info_basic tr:nth-child(3) > th:nth-child(1) |  |
        element = self.driver.find_element(By.CSS_SELECTOR, "#patient_info_basic tr:nth-child(3) > th:nth-child(1)")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        # 39 | click | css=tr:nth-child(3) > .btpd:nth-child(2) > .bt_txt_align2 |  |
        self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(3) > .btpd:nth-child(2) > .bt_txt_align2").click()
        # 40 | click | css=tr:nth-child(3) > .btpd:nth-child(2) > .bt_txt_align2 |  |
        self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(3) > .btpd:nth-child(2) > .bt_txt_align2").click()
        # 41 | doubleClick | css=tr:nth-child(3) > .btpd:nth-child(2) > .bt_txt_align2 |  |
        element = self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(3) > .btpd:nth-child(2) > .bt_txt_align2")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        # 42 | click | css=#patient_info_basic tr:nth-child(3) > th:nth-child(3) |  |
        self.driver.find_element(By.CSS_SELECTOR, "#patient_info_basic tr:nth-child(3) > th:nth-child(3)").click()
        # 43 | click | css=#patient_info_basic tr:nth-child(3) > th:nth-child(3) |  |
        self.driver.find_element(By.CSS_SELECTOR, "#patient_info_basic tr:nth-child(3) > th:nth-child(3)").click()
        # 44 | doubleClick | css=#patient_info_basic tr:nth-child(3) > th:nth-child(3) |  |
        element = self.driver.find_element(By.CSS_SELECTOR, "#patient_info_basic tr:nth-child(3) > th:nth-child(3)")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        # 45 | click | css=tr:nth-child(3) > .btpd:nth-child(4) > .bt_txt_align2 |  |
        self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(3) > .btpd:nth-child(4) > .bt_txt_align2").click()
        # 46 | click | css=#patient_info_basic tr:nth-child(4) > th:nth-child(1) |  |
        self.driver.find_element(By.CSS_SELECTOR, "#patient_info_basic tr:nth-child(4) > th:nth-child(1)").click()
        # 47 | click | css=#patient_info_basic tr:nth-child(4) > th:nth-child(1) |  |
        self.driver.find_element(By.CSS_SELECTOR, "#patient_info_basic tr:nth-child(4) > th:nth-child(1)").click()
        # 48 | doubleClick | css=#patient_info_basic tr:nth-child(4) > th:nth-child(1) |  |
        element = self.driver.find_element(By.CSS_SELECTOR, "#patient_info_basic tr:nth-child(4) > th:nth-child(1)")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        # 49 | click | css=#patient_info_basic tr:nth-child(4) > td:nth-child(2) |  |
        self.driver.find_element(By.CSS_SELECTOR, "#patient_info_basic tr:nth-child(4) > td:nth-child(2)").click()
        # 50 | click | css=#patient_info_basic tr:nth-child(4) > td:nth-child(2) |  |
        self.driver.find_element(By.CSS_SELECTOR, "#patient_info_basic tr:nth-child(4) > td:nth-child(2)").click()
        # 51 | doubleClick | css=#patient_info_basic tr:nth-child(4) > td:nth-child(2) |  |
        element = self.driver.find_element(By.CSS_SELECTOR, "#patient_info_basic tr:nth-child(4) > td:nth-child(2)")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        # 52 | click | css=.m_sp:nth-child(3) |  |
        self.driver.find_element(By.CSS_SELECTOR, ".m_sp:nth-child(3)").click()
        # 53 | click | css=.m_sp:nth-child(3) |  |
        self.driver.find_element(By.CSS_SELECTOR, ".m_sp:nth-child(3)").click()
        # 54 | doubleClick | css=.m_sp:nth-child(3) |  |
        element = self.driver.find_element(By.CSS_SELECTOR, ".m_sp:nth-child(3)")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        # 55 | click | css=.m_sp:nth-child(3) |  |
        self.driver.find_element(By.CSS_SELECTOR, ".m_sp:nth-child(3)").click()
        # 56 | click | css=.btpd > .m_sp |  |
        self.driver.find_element(By.CSS_SELECTOR, ".btpd > .m_sp").click()
        # 57 | click | css=.btpd > .m_sp |  |
        self.driver.find_element(By.CSS_SELECTOR, ".btpd > .m_sp").click()
        # 58 | doubleClick | css=.btpd > .m_sp |  |
        element = self.driver.find_element(By.CSS_SELECTOR, ".btpd > .m_sp")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        # 59 | click | css=.btpd > .m_sp |  |
        self.driver.find_element(By.CSS_SELECTOR, ".btpd > .m_sp").click()
        # 60 | click | css=#patient_info_basic tr:nth-child(5) > th:nth-child(1) |  |
        self.driver.find_element(By.CSS_SELECTOR, "#patient_info_basic tr:nth-child(5) > th:nth-child(1)").click()
        # 61 | click | css=#patient_info_basic tr:nth-child(5) > th:nth-child(1) |  |
        self.driver.find_element(By.CSS_SELECTOR, "#patient_info_basic tr:nth-child(5) > th:nth-child(1)").click()
        # 62 | doubleClick | css=#patient_info_basic tr:nth-child(5) > th:nth-child(1) |  |
        element = self.driver.find_element(By.CSS_SELECTOR, "#patient_info_basic tr:nth-child(5) > th:nth-child(1)")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        # 63 | click | css=tr:nth-child(5) > .dotdotdot:nth-child(2) |  |
        self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(5) > .dotdotdot:nth-child(2)").click()
        # 64 | click | css=tr:nth-child(5) > .dotdotdot:nth-child(2) |  |
        self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(5) > .dotdotdot:nth-child(2)").click()
        # 65 | doubleClick | css=tr:nth-child(5) > .dotdotdot:nth-child(2) |  |
        element = self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(5) > .dotdotdot:nth-child(2)")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        # 66 | click | css=tr:nth-child(5) > .dotdotdot:nth-child(2) |  |
        self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(5) > .dotdotdot:nth-child(2)").click()
        # 67 | click | css=#patient_info_basic tr:nth-child(5) > th:nth-child(3) |  |
        self.driver.find_element(By.CSS_SELECTOR, "#patient_info_basic tr:nth-child(5) > th:nth-child(3)").click()
        # 68 | click | css=#patient_info_basic tr:nth-child(5) > th:nth-child(3) |  |
        self.driver.find_element(By.CSS_SELECTOR, "#patient_info_basic tr:nth-child(5) > th:nth-child(3)").click()
        # 69 | doubleClick | css=#patient_info_basic tr:nth-child(5) > th:nth-child(3) |  |
        element = self.driver.find_element(By.CSS_SELECTOR, "#patient_info_basic tr:nth-child(5) > th:nth-child(3)")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        # 70 | click | css=#patient_info_basic tr:nth-child(5) > .dotdotdot:nth-child(4) |  |
        self.driver.find_element(By.CSS_SELECTOR, "#patient_info_basic tr:nth-child(5) > .dotdotdot:nth-child(4)").click()
        # 71 | click | css=#patient_info_basic tr:nth-child(5) > .dotdotdot:nth-child(4) |  |
        self.driver.find_element(By.CSS_SELECTOR, "#patient_info_basic tr:nth-child(5) > .dotdotdot:nth-child(4)").click()
        # 72 | doubleClick | css=#patient_info_basic tr:nth-child(5) > .dotdotdot:nth-child(4) |  |
        element = self.driver.find_element(By.CSS_SELECTOR, "#patient_info_basic tr:nth-child(5) > .dotdotdot:nth-child(4)")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        # 73 | click | css=#patient_info_basic tr:nth-child(5) > .dotdotdot:nth-child(4) |  |
        self.driver.find_element(By.CSS_SELECTOR, "#patient_info_basic tr:nth-child(5) > .dotdotdot:nth-child(4)").click()
        # 74 | click | css=.sm:nth-child(5) |  |
        self.driver.find_element(By.CSS_SELECTOR, ".sm:nth-child(5)").click()
        # 75 | click | css=.sm:nth-child(5) |  |
        self.driver.find_element(By.CSS_SELECTOR, ".sm:nth-child(5)").click()
        # 76 | doubleClick | css=.sm:nth-child(5) |  |
        element = self.driver.find_element(By.CSS_SELECTOR, ".sm:nth-child(5)")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        # 77 | click | css=.sm:nth-child(5) |  |
        self.driver.find_element(By.CSS_SELECTOR, ".sm:nth-child(5)").click()
        # 78 | click | css=.sm:nth-child(5) |  |
        self.driver.find_element(By.CSS_SELECTOR, ".sm:nth-child(5)").click()
        # 79 | click | css=#patient_info_basic tr:nth-child(5) > td:nth-child(6) |  |
        self.driver.find_element(By.CSS_SELECTOR, "#patient_info_basic tr:nth-child(5) > td:nth-child(6)").click()
        # 80 | click | css=#patient_info_basic tr:nth-child(5) > td:nth-child(6) |  |
        self.driver.find_element(By.CSS_SELECTOR, "#patient_info_basic tr:nth-child(5) > td:nth-child(6)").click()
        # 81 | doubleClick | css=#patient_info_basic tr:nth-child(5) > td:nth-child(6) |  |
        element = self.driver.find_element(By.CSS_SELECTOR, "#patient_info_basic tr:nth-child(5) > td:nth-child(6)")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        # 82 | click | css=#patient_info_basic tr:nth-child(5) > td:nth-child(6) |  |
        self.driver.find_element(By.CSS_SELECTOR, "#patient_info_basic tr:nth-child(5) > td:nth-child(6)").click()
        # 83 | click | css=#patient_info_basic tr:nth-child(5) > td:nth-child(6) |  |
        self.driver.find_element(By.CSS_SELECTOR, "#patient_info_basic tr:nth-child(5) > td:nth-child(6)").click()
        # 84 | click | css=tr:nth-child(6) > th |  |
        self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(6) > th").click()
        # 85 | click | css=tr:nth-child(6) > th |  |
        self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(6) > th").click()
        # 86 | doubleClick | css=tr:nth-child(6) > th |  |
        element = self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(6) > th")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        # 87 | click | css=.dotdotdot:nth-child(1) |  |
        self.driver.find_element(By.CSS_SELECTOR, ".dotdotdot:nth-child(1)").click()
        # 88 | click | css=.dotdotdot:nth-child(1) |  |
        self.driver.find_element(By.CSS_SELECTOR, ".dotdotdot:nth-child(1)").click()
        # 89 | doubleClick | css=.dotdotdot:nth-child(1) |  |
        element = self.driver.find_element(By.CSS_SELECTOR, ".dotdotdot:nth-child(1)")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        # 90 | click | css=.dotdotdot:nth-child(1) |  |
        self.driver.find_element(By.CSS_SELECTOR, ".dotdotdot:nth-child(1)").click()
        # 91 | click | css=.dotdotdot:nth-child(1) |  |
        self.driver.find_element(By.CSS_SELECTOR, ".dotdotdot:nth-child(1)").click()
        # 92 | click | css=.dotdotdot:nth-child(1) |  |
        self.driver.find_element(By.CSS_SELECTOR, ".dotdotdot:nth-child(1)").click()
        # 93 | click | css=.dotdotdot:nth-child(1) |  |
        self.driver.find_element(By.CSS_SELECTOR, ".dotdotdot:nth-child(1)").click()
        # 94 | doubleClick | css=.dotdotdot:nth-child(1) |  |
        element = self.driver.find_element(By.CSS_SELECTOR, ".dotdotdot:nth-child(1)")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        # 95 | click | css=.dotdotdot:nth-child(1) |  |
        self.driver.find_element(By.CSS_SELECTOR, ".dotdotdot:nth-child(1)").click()
        # 96 | click | css=tr:nth-child(7) > th:nth-child(1) |  |
        self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(7) > th:nth-child(1)").click()
        # 97 | click | css=tr:nth-child(7) > th:nth-child(1) |  |
        self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(7) > th:nth-child(1)").click()
        # 98 | doubleClick | css=tr:nth-child(7) > th:nth-child(1) |  |
        element = self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(7) > th:nth-child(1)")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        # 99 | click | css=tr:nth-child(7) > .dotdotdot:nth-child(2) |  |
        self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(7) > .dotdotdot:nth-child(2)").click()
        # 100 | click | css=tr:nth-child(7) > .dotdotdot:nth-child(2) |  |
        self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(7) > .dotdotdot:nth-child(2)").click()
        # 101 | doubleClick | css=tr:nth-child(7) > .dotdotdot:nth-child(2) |  |
        element = self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(7) > .dotdotdot:nth-child(2)")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        # 102 | click | css=tr:nth-child(7) > .dotdotdot:nth-child(2) |  |
        self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(7) > .dotdotdot:nth-child(2)").click()
        # 103 | click | css=tr:nth-child(7) > th:nth-child(3) |  |
        self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(7) > th:nth-child(3)").click()
        # 104 | click | css=tr:nth-child(7) > th:nth-child(3) |  |
        self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(7) > th:nth-child(3)").click()
        # 105 | doubleClick | css=tr:nth-child(7) > th:nth-child(3) |  |
        element = self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(7) > th:nth-child(3)")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        # 106 | click | css=tr:nth-child(7) > .dotdotdot:nth-child(4) |  |
        self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(7) > .dotdotdot:nth-child(4)").click()
        # 107 | click | css=tr:nth-child(7) > .dotdotdot:nth-child(4) |  |
        self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(7) > .dotdotdot:nth-child(4)").click()
        # 108 | doubleClick | css=tr:nth-child(7) > .dotdotdot:nth-child(4) |  |
        element = self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(7) > .dotdotdot:nth-child(4)")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        # 109 | click | css=tr:nth-child(7) > .dotdotdot:nth-child(4) |  |
        self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(7) > .dotdotdot:nth-child(4)").click()

    def test_getWardList(self):
        # Test name: GetWardList
        # Step # | name | target | value | comment
        # 1 | open |
        # https://work.carefor.co.kr/#cGFnZXx7J3R5cGUnOidsZWZ0X3N1YjEnLCAndmlldyc6Jy9wYXRpZW50L3ZpZXcucGF0aWVudF9tYW5hZ2UnfSV7InRpdGxlIjoiMS0xLuyImOq4ieyekOygleuztCDqtIDrpqwiLCJldmFsIjoiNDciLCJtb3ZlX3Njcm9sbCI6dHJ1ZX18bGVmdF9zdWIx
        # |  |
        self.driver.get("https://work.carefor.co.kr/#cGFnZXx7J3R5cGUnOidsZWZ0X3N1YjEnLCAndmlldyc6Jy9wYXRpZW50L3ZpZXcucGF0aWVudF9tYW5hZ2UnfSV7InRpdGxlIjoiMS0xLuyImOq4ieyekOygleuztCDqtIDrpqwiLCJldmFsIjoiNDciLCJtb3ZlX3Njcm9sbCI6dHJ1ZX18bGVmdF9zdWIx")
        # 2 | setWindowSize | 1267x1791 |  |
        self.driver.set_window_size(1610, 1046)
        # 3 | click | css=.spot_color > .no_lf |  |
        self.driver.find_element(By.CSS_SELECTOR, ".spot_color > .no_lf").click()
        # 4 | click | css=.spot_color:nth-child(2) |  |
        self.driver.find_element(By.CSS_SELECTOR, ".spot_color:nth-child(2)").click()
        # 5 | click | css=.cr > .spot_color:nth-child(2) |  |
        self.driver.find_element(By.CSS_SELECTOR, ".cr > .spot_color:nth-child(2)").click()
        # 6 | click | css=.spot_color:nth-child(2) |  |
        self.driver.find_element(By.CSS_SELECTOR, ".spot_color:nth-child(2)").click()
        # 7 | click | css=.spot_color:nth-child(2) |  |
        self.driver.find_element(By.CSS_SELECTOR, ".spot_color:nth-child(2)").click()
        # 8 | click | css=.spot_color:nth-child(2) |  |
        self.driver.find_element(By.CSS_SELECTOR, ".spot_color:nth-child(2)").click()
        # 9 | click | css=.spot_color:nth-child(2) |  |
        self.driver.find_element(By.CSS_SELECTOR, ".spot_color:nth-child(2)").click()
        # 10 | click | css=.cr:nth-child(7) > .no_lf |  |
        self.driver.find_element(By.CSS_SELECTOR, ".cr:nth-child(7) > .no_lf").click()
        # 11 | click | id=ctnr_patient_list_table |  |
        self.driver.find_element(By.ID, "ctnr_patient_list_table").click()
        # 12 | click | css=.cr:nth-child(7) > .no_lf |  |
        self.driver.find_element(By.CSS_SELECTOR, ".cr:nth-child(7) > .no_lf").click()

    def test_getStaffInfo(self):
        # Test name: GetStaffInfo
        # Step # | name | target | value | comment
        # 1 | open |
        # https://work.carefor.co.kr/#cGFnZXx7J3R5cGUnOidsZWZ0X3N1YjEnLCAndmlldyc6Jy9wYXRpZW50L3ZpZXcucGF0aWVudF9tYW5hZ2UnfSV7InRpdGxlIjoiMS0xLuyImOq4ieyekOygleuztCDqtIDrpqwiLCJldmFsIjoiNDciLCJtb3ZlX3Njcm9sbCI6dHJ1ZX18bGVmdF9zdWIx
        # |  |
        self.driver.get("https://work.carefor.co.kr/#cGFnZXx7J3R5cGUnOidsZWZ0X3N1YjEnLCAndmlldyc6Jy9wYXRpZW50L3ZpZXcucGF0aWVudF9tYW5hZ2UnfSV7InRpdGxlIjoiMS0xLuyImOq4ieyekOygleuztCDqtIDrpqwiLCJldmFsIjoiNDciLCJtb3ZlX3Njcm9sbCI6dHJ1ZX18bGVmdF9zdWIx")
        # # 2 | setWindowSize | 2437x1791 |  |
        # self.driver.set_window_size(1610, 1046)
        # # 3 | click | css=.btn_area > .btn_type3 |  |
        # self.driver.find_element(By.CSS_SELECTOR, ".btn_area > .btn_type3").click()
        # 4 | click | css=.leftmenu > ul > li:nth-child(8) |  |

        #
        # Open Staff Management Screen
        #
        self.driver.find_element(By.CSS_SELECTOR, ".leftmenu > ul > li:nth-child(8)").click()
# # 5 | click | css=#left_sub8 li:nth-child(1) |  |
        self.driver.find_element(By.CSS_SELECTOR, "#left_sub8 li:nth-child(1)").click()
        # 6 | click | css=.spot_color:nth-child(3) |  |

       #
       #  Select a staff
       #
        self.driver.find_element(By.CSS_SELECTOR, ".spot_color:nth-child(3)").click()

       #
       #  Get values
       #
        # 7 | click | css=.tbl_type1:nth-child(3) th:nth-child(2) |  |
        self.driver.find_element(By.CSS_SELECTOR, ".tbl_type1:nth-child(3) th:nth-child(2)").click()
        # 8 | click | css=.tbl_type1:nth-child(3) td:nth-child(3) |  |
        self.driver.find_element(By.CSS_SELECTOR, ".tbl_type1:nth-child(3) td:nth-child(3)").click()

        # 9 | click | css=.tbl_type1:nth-child(3) th:nth-child(4) |  |
        self.driver.find_element(By.CSS_SELECTOR, ".tbl_type1:nth-child(3) th:nth-child(4)").click()
        # 10 | click | css=.tbl_type1:nth-child(3) td:nth-child(5) |  |
        self.driver.find_element(By.CSS_SELECTOR, ".tbl_type1:nth-child(3) td:nth-child(5)").click()

        # 11 | click | css=.tbl_type1 th:nth-child(6) |  |
        self.driver.find_element(By.CSS_SELECTOR, ".tbl_type1 th:nth-child(6)").click()
        # 12 | click | css=.tbl_type1 tr:nth-child(1) > td:nth-child(7) |  |
        self.driver.find_element(By.CSS_SELECTOR, ".tbl_type1 tr:nth-child(1) > td:nth-child(7)").click()

        # 13 | click | css=.tbl_type1:nth-child(3) tr:nth-child(2) > th:nth-child(1) |  |
        self.driver.find_element(By.CSS_SELECTOR, ".tbl_type1:nth-child(3) tr:nth-child(2) > th:nth-child(1)").click()
        # 14 | click | css=tr:nth-child(2) > .btpd:nth-child(2) > .bt_txt_align2 |  |
        self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) > .btpd:nth-child(2) > .bt_txt_align2").click()

        # 15 | click | css=.tbl_type1:nth-child(3) tr:nth-child(2) > th:nth-child(3) |  |
        self.driver.find_element(By.CSS_SELECTOR, ".tbl_type1:nth-child(3) tr:nth-child(2) > th:nth-child(3)").click()
        # 16 | click | css=.tbl_type1:nth-child(3) tr:nth-child(2) > td:nth-child(4) |  |
        self.driver.find_element(By.CSS_SELECTOR, ".tbl_type1:nth-child(3) tr:nth-child(2) > td:nth-child(4)").click()

        # 17 | click | css=.tbl_type1:nth-child(3) th:nth-child(5) |  |
        self.driver.find_element(By.CSS_SELECTOR, ".tbl_type1:nth-child(3) th:nth-child(5)").click()
        # 18 | click | css=.btpd:nth-child(6) > .bt_txt_align2 |  |
        self.driver.find_element(By.CSS_SELECTOR, ".btpd:nth-child(6) > .bt_txt_align2").click()

        # 19 | click | css=.tbl_type1:nth-child(3) tr:nth-child(3) > th:nth-child(1) |  |
        self.driver.find_element(By.CSS_SELECTOR, ".tbl_type1:nth-child(3) tr:nth-child(3) > th:nth-child(1)").click()
        # 20 | click | css=.tbl_type1:nth-child(3) tr:nth-child(3) > td:nth-child(2) |  |
        self.driver.find_element(By.CSS_SELECTOR, ".tbl_type1:nth-child(3) tr:nth-child(3) > td:nth-child(2)").click()

        # 21 | click | css=tr:nth-child(3) > th:nth-child(3) |  |
        self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(3) > th:nth-child(3)").click()
        # 22 | click | css=tr:nth-child(3) .dotdotdot |  |
        self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(3) .dotdotdot").click()

        # 23 | click | css=.tbl_type1:nth-child(3) tr:nth-child(4) > th:nth-child(1) |  |
        self.driver.find_element(By.CSS_SELECTOR, ".tbl_type1:nth-child(3) tr:nth-child(4) > th:nth-child(1)").click()
        # 24 | click | css=tr:nth-child(4) > .dotdotdot |  |
        self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(4) > .dotdotdot").click()

        # 25 | click | css=tr:nth-child(4) > th:nth-child(3) |  |
        self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(4) > th:nth-child(3)").click()
        # 26 | click | css=tr:nth-child(4) > td > .dotdotdot |  |
        self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(4) > td > .dotdotdot").click()

        # 27 | click | css=.tbl_type1:nth-child(3) tr:nth-child(5) > th |  |
        self.driver.find_element(By.CSS_SELECTOR, ".tbl_type1:nth-child(3) tr:nth-child(5) > th").click()
        # 28 | click | css=tr:nth-child(5) .bt_txt_align2 |  |
        self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(5) .bt_txt_align2").click()

        # 29 | click | css=.tbl_type1 tr:nth-child(6) > th:nth-child(1) |  |
        self.driver.find_element(By.CSS_SELECTOR, ".tbl_type1 tr:nth-child(6) > th:nth-child(1)").click()
        # 30 | click | css=tr:nth-child(6) .bt_txt_align2 |  |
        self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(6) .bt_txt_align2").click()

        # 31 | click | css=tr:nth-child(6) > th:nth-child(3) |  |
        self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(6) > th:nth-child(3)").click()
        # 32 | click | css=.tbl_type1 tr:nth-child(6) > td:nth-child(4) |  |
        self.driver.find_element(By.CSS_SELECTOR, ".tbl_type1 tr:nth-child(6) > td:nth-child(4)").click()

        # 33 | click | css=.m_sp:nth-child(3) |  |
        self.driver.find_element(By.CSS_SELECTOR, ".m_sp:nth-child(3)").click()
        # 34 | click | css=.tbl_type1 tr:nth-child(7) > td:nth-child(4) |  |
        self.driver.find_element(By.CSS_SELECTOR, ".tbl_type1 tr:nth-child(7) > td:nth-child(4)").click()

        # 35 | click | css=.tbl_type1 th:nth-child(8) |  |
        self.driver.find_element(By.CSS_SELECTOR, ".tbl_type1 th:nth-child(8)").click()
        # 36 | click | css=.inpd |  |
        self.driver.find_element(By.CSS_SELECTOR, ".inpd").click()

        # 37 | click | css=.tbl_type1 tr:nth-child(7) > th:nth-child(1) |  |
        self.driver.find_element(By.CSS_SELECTOR, ".tbl_type1 tr:nth-child(7) > th:nth-child(1)").click()
        # 38 | click | css=tr:nth-child(7) > .dotdotdot |  |
        self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(7) > .dotdotdot").click()

        # 39 | click | css=.pic_div > img |  |
        self.driver.find_element(By.CSS_SELECTOR, ".pic_div > img").click()

    def test_getStaffList(self):
        # Test name: GetStaffList
        # Step # | name | target | value | comment
        # 1 | open |
        # https://work.carefor.co.kr/#cGFnZXx7J3R5cGUnOidsZWZ0X3N1YjEnLCAndmlldyc6Jy9wYXRpZW50L3ZpZXcucGF0aWVudF9tYW5hZ2UnfSV7InRpdGxlIjoiMS0xLuyImOq4ieyekOygleuztCDqtIDrpqwiLCJldmFsIjoiNDciLCJtb3ZlX3Njcm9sbCI6dHJ1ZX18bGVmdF9zdWIx
        # |  |
        self.driver.get("https://work.carefor.co.kr/#cGFnZXx7J3R5cGUnOidsZWZ0X3N1YjEnLCAndmlldyc6Jy9wYXRpZW50L3ZpZXcucGF0aWVudF9tYW5hZ2UnfSV7InRpdGxlIjoiMS0xLuyImOq4ieyekOygleuztCDqtIDrpqwiLCJldmFsIjoiNDciLCJtb3ZlX3Njcm9sbCI6dHJ1ZX18bGVmdF9zdWIx")
        # 2 | setWindowSize | 1267x1791 |  |
        self.driver.set_window_size(1610, 1046)
        # 3 | click | css=.layer_close:nth-child(1) img |  |
        self.driver.find_element(By.CSS_SELECTOR, ".layer_close:nth-child(1) img").click()
        # 4 | click | css=.leftmenu > ul > li:nth-child(8) |  |
        self.driver.find_element(By.CSS_SELECTOR, ".leftmenu > ul > li:nth-child(8)").click()
        # 5 | click | css=#left_sub8 li:nth-child(1) |  |
        self.driver.find_element(By.CSS_SELECTOR, "#left_sub8 li:nth-child(1)").click()
        # 6 | select | xpath=//*[@id="staff_list_table"]/tbody/tr[10]/td[1]/text()[1] | 10 |
        dropdown = self.driver.find_element(By.XPATH, "//*[@id=\"staff_list_table\"]/tbody/tr[10]/td[1]/text()[1]")
        dropdown.find_element(By.XPATH, "//option[. = '10']").click()
